name: Wine-WoW64-NTSYNC CI

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Build Wine
        run: |
          sudo apt update
          sudo apt install debootstrap perl git wget xz-utils bubblewrap autoconf
          sudo tar -C /opt -xpf /opt/Bootstraps/bootstraps.tar.xz
          chmod +x build_wine.sh
          export WINE_VERSION="latest"
          export EXPERIMENTAL_WOW64="true"
          WINE_BRANCH=vanilla ./build_wine.sh
          WINE_BRANCH=staging ./build_wine.sh
          WINE_BRANCH=staging-tkg ./build_wine.sh
          WINE_BRANCH=staging-tkg-ntsync ./build_wine.sh
          sha256sum *.tar.xz
      - uses: actions/upload-artifact@v4
        with:
          name: Wine-WoW64-NTSYNC
          path: ./*.tar.xz
